const items=[["dashboard","▦","Dashboard"],["phones","📱","New Phones"],["second","♻","Second-Hand"],["accessories","◈","Accessories"],["purchase","↓","Purchase"],["sales","↑","Sales"],["inventory","▣","Inventory"],["repair","⚒","Repairing"],["customers","♙","Customers"],["billing","▤","Billing"],["reports","◒","Reports"],["subscription","◇","Subscription"]];
function shopLogin(){if(loginId.value.trim()!=="SHOP001"||pin.value.trim()!=="1234")return toast("Login details गलत हैं");login.classList.add("hidden");app.classList.remove("hidden");nav.innerHTML=items.map(x=>`<button class="nav" data-page="${x[0]}" onclick="render('${x[0]}')">${x[1]}<span>${x[2]}</span></button>`).join("");render("dashboard")}
function stat(v,l,t=""){return `<div class="card stat"><small>${l}</small><strong>${v}</strong><div class="trend">${t}</div></div>`}
function tile(i,b,s,p){return `<button class="tile" onclick="render('${p}')"><div class="icon">${i}</div><b>${b}</b><small>${s}</small></button>`}
function table(){return `<div class="table-wrap"><table class="table"><tr><th>ID</th><th>Customer</th><th>Details</th><th>Amount</th><th>Status</th></tr><tr><td>MEM-1042</td><td>Rahul</td><td>iPhone 15</td><td>₹55,000</td><td><span class="badge">PAID</span></td></tr><tr><td>MEM-1041</td><td>Aman</td><td>Accessories</td><td>₹7,499</td><td><span class="badge">PAID</span></td></tr><tr><td>MEM-1040</td><td>Neha</td><td>Samsung A56</td><td>₹34,999</td><td><span class="badge warn">DUE</span></td></tr></table></div>`}
function modulePage(h,s){return `<div class="hero"><div><span class="eyebrow">MEMORY MODULE</span><h1>${h}</h1><div class="muted">${s}</div></div><button class="primary" onclick="toast('Add New')">+ Add New</button></div><div class="section card">${table()}</div>`}
function render(p){pageTitle.textContent=p==="dashboard"?"Dashboard":p[0].toUpperCase()+p.slice(1);document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===p));let c;if(p==="dashboard")c=`<div class="hero"><div><span class="eyebrow">SHOP ADMIN</span><h1>दुकान का पूरा काम एक जगह।</h1><div class="muted">MEMORY Mobile Shop Workspace</div></div><button class="primary" onclick="render('sales')">+ New Sale</button></div><div class="stats">${stat("₹48,500","आज की Sales","+12.5%")}${stat("₹7,840","आज का Profit","+8.2%")}${stat("42","Phone Stock","8 low stock")}${stat("186","Accessories","24 sold")}</div><div class="section"><div class="grid">${tile("📱","New Phones","Stock & sale","phones")}${tile("♻","Second-Hand","Buy & sell","second")}${tile("◈","Accessories","Stock & sale","accessories")}${tile("⚒","Repairing","Job cards","repair")}</div></div><div class="section card">${table()}</div>`;else c=modulePage(p==="phones"?"New Phone Management":p==="second"?"Second-Hand Management":p==="accessories"?"Accessories":p[0].toUpperCase()+p.slice(1),"Module ready for next development.");content.innerHTML=c;sidebar.classList.remove("open")}
function showSuper(){login.classList.add("hidden");app.classList.add("hidden");superadmin.classList.remove("hidden");superadmin.innerHTML=`<div style="padding:28px"><div class="hero"><div><span class="eyebrow">MEMORY · SUPER ADMIN</span><h1>Master Dashboard</h1><div class="muted">यह page केवल owner के लिए है।</div></div><button class="primary" onclick="location.href=location.pathname.replace(/\/superadmin\/?$/,'/')">Shop Admin</button></div><div class="stats">${stat("128","Total Shops","+12 this month")}${stat("117","Active Shops")}${stat("₹1,27,872","Monthly Revenue","+8.2%")}${stat("7","Expiring Soon")}</div><div class="section"><div class="grid">${tile("⌂","All Shops","सभी rented shops","dashboard")}${tile("◇","Subscriptions","Active / expired","dashboard")}${tile("₹","Payments","Payment history","dashboard")}${tile("⚙","Settings","Platform control","dashboard")}</div></div><div class="section card"><h3>Recent Shops</h3>${table()}</div></div>`}
function toggleSidebar(){sidebar.classList.toggle("open")}function toggleTheme(){document.body.classList.toggle("dark")}function toast(t){toastBox=t;const x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)}
if(location.pathname.toLowerCase().endsWith("/superadmin")||location.pathname.toLowerCase().endsWith("/superadmin/"))showSuper();
