const $=id=>document.getElementById(id);let role="";
const configs={
 super:{name:"Super Admin",id:"SUPER001",pin:"2580",avatar:"SA",sub:"Platform Control",items:[["dashboard","▦","Dashboard"],["shops","⌂","All Shops"],["subscriptions","◇","Subscriptions"],["payments","₹","Payments"],["plans","◫","Plans"],["analytics","◒","Platform Analytics"],["features","◆","Feature Control"],["settings","⚙","Settings"]]},
 shop:{name:"Shop Admin",id:"SHOP001",pin:"1234",avatar:"SA",sub:"Shop Control",items:[["dashboard","▦","Dashboard"],["phones","📱","New Phones"],["second","♻","Second-Hand"],["accessories","◈","Accessories"],["purchase","↓","Purchase"],["sales","↑","Sales"],["inventory","▣","Inventory"],["repair","⚒","Repairing"],["customers","♙","Customers"],["billing","▤","Billing"],["reports","◒","Reports"],["staff","♟","Staff"],["subscription","◇","Subscription"]]},
 staff:{name:"Staff",id:"STAFF001",pin:"1111",avatar:"ST",sub:"Daily Work",items:[["dashboard","▦","Dashboard"],["sales","↑","Sales"],["inventory","▣","Inventory"],["repair","⚒","Repairing"],["customers","♙","Customers"],["billing","▤","Billing"]]}
};
function login(){const r=$("role").value,id=$("loginId").value.trim(),pin=$("pin").value.trim(),c=configs[r];if(id!==c.id||pin!==c.pin)return toast("Login details गलत हैं");role=r;$("login").classList.add("hidden");$("app").classList.remove("hidden");setup();render("dashboard")}
function setup(){const c=configs[role];$("brandSub").textContent=c.sub;$("accountName").textContent=c.name;$("accountId").textContent=c.id;$("avatar").textContent=c.avatar;$("nav").innerHTML=c.items.map(x=>`<button class="nav" data-page="${x[0]}" onclick="render('${x[0]}')">${x[1]}<span>${x[2]}</span></button>`).join("")}
function stat(v,l,t=""){return `<div class="card stat"><small>${l}</small><strong>${v}</strong><div class="trend">${t}</div></div>`}
function tile(i,b,s,p){return `<button class="tile" onclick="render('${p}')"><div class="icon">${i}</div><b>${b}</b><small>${s}</small></button>`}
function table(rows){return `<div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Name</th><th>Details</th><th>Amount</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>`<td>${i===4?`<span class="badge ${x==="DUE"?"warn":x==="EXPIRED"?"bad":""}">${x}</span>`:x}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function shopModule(h,s,items){return `<div class="hero"><div><span class="eyebrow">MEMORY MODULE</span><h1>${h}</h1><div class="muted">${s}</div></div><button class="primary" onclick="toast('Add New module')">+ Add New</button></div><div class="grid">${items.map(x=>tile("◈",x,"Open module","dashboard")).join("")}</div><div class="section card"><div class="section-head"><h3>Recent Activity</h3><button class="secondary" onclick="toast('Search')">Search</button></div>${table([["MEM-1042","Rahul","iPhone 15","₹55,000","PAID"],["MEM-1041","Aman","Accessories","₹7,499","PAID"],["MEM-1040","Neha","Samsung A56","₹34,999","DUE"]])}</div>`}
function render(p){$("pageTitle").textContent=p==="dashboard"?"Dashboard":p.replace(/^\w/,x=>x.toUpperCase());document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===p));$("content").innerHTML=role==="super"?superPage(p):shopPage(p);$("sidebar").classList.remove("open")}
function superPage(p){
if(p==="dashboard")return `<div class="hero"><div><span class="eyebrow">SUPER ADMIN</span><h1>MEMORY Platform Control</h1><div class="muted">सभी shops, subscriptions और payments का master dashboard.</div></div><button class="primary" onclick="toast('Create Shop form')">+ Create Shop</button></div><div class="stats">${stat("128","Total Shops","+12 this month")}${stat("117","Active Shops","91.4% active")}${stat("₹1,27,872","Monthly Revenue","+8.2%")}${stat("7","Expiring Soon","Next 7 days")}</div><div class="section"><div class="grid">${tile("⌂","All Shops","Manage every shop","shops")}${tile("◇","Subscriptions","Active / expired","subscriptions")}${tile("₹","Payments","Payment history","payments")}${tile("◫","Plans","Pricing plans","plans")}</div></div><div class="section card"><div class="section-head"><h3>Recent Shops</h3><button class="secondary" onclick="render('shops')">View All</button></div>${table([["SHOP001","Aman Mobile","Premium","₹999","PAID"],["SHOP002","Sharma Telecom","Standard","₹699","PAID"],["SHOP003","City Phones","Premium","₹999","DUE"]])}</div>`;
if(p==="shops")return `<div class="hero"><div><span class="eyebrow">SUPER ADMIN</span><h1>All Shops</h1><div class="muted">सभी rented shops manage करें।</div></div><button class="primary" onclick="toast('Create Shop form')">+ Create Shop</button></div><div class="card">${table([["SHOP001","Aman Mobile","Premium","₹999","PAID"],["SHOP002","Sharma Telecom","Standard","₹699","PAID"],["SHOP003","City Phones","Premium","₹999","EXPIRED"]])}</div>`;
if(p==="subscriptions")return `<div class="hero"><div><span class="eyebrow">SUBSCRIPTIONS</span><h1>Subscription Control</h1></div><div class="stats">${stat("117","Active")}${stat("7","Expiring Soon")}${stat("4","Expired")}${stat("14","Renewed Today")}</div></div><div class="section card">${table([["SHOP001","Aman Mobile","Premium","22 Sep 2026","PAID"],["SHOP002","Sharma Telecom","Standard","18 Sep 2026","PAID"],["SHOP003","City Phones","Premium","22 Aug 2026","EXPIRED"]])}</div>`;
if(p==="payments")return `<div class="hero"><div><span class="eyebrow">PAYMENTS</span><h1>Payment Center</h1></div></div><div class="stats">${stat("₹1,27,872","This Month","+8.2%")}${stat("₹6,999","Today","+5 payments")}${stat("14","Successful")}${stat("2","Failed")}</div><div class="section card">${table([["PAY-1001","Aman Mobile","Premium Renewal","₹999","PAID"],["PAY-1000","Sharma Telecom","Standard Renewal","₹699","PAID"],["PAY-0999","City Phones","Premium Renewal","₹999","DUE"]])}</div>`;
if(p==="plans")return `<div class="hero"><div><span class="eyebrow">PLANS</span><h1>Subscription Plans</h1></div><button class="primary" onclick="toast('New Plan')">+ New Plan</button></div><div class="grid"><div class="card"><h3>Basic</h3><div class="price">₹499</div><p>/ month</p><p>Core shop management</p></div><div class="card"><h3>Standard</h3><div class="price">₹699</div><p>/ month</p><p>Inventory + billing + reports</p></div><div class="card"><h3>Premium</h3><div class="price">₹999</div><p>/ month</p><p>Full MEMORY features</p></div></div>`;
if(p==="analytics")return `<div class="hero"><div><span class="eyebrow">PLATFORM ANALYTICS</span><h1>MEMORY Analytics</h1></div></div><div class="stats">${stat("128","Shops")}${stat("3,842","Active Users")}${stat("₹12.7L","Revenue")}${stat("94.2%","Retention")}</div>`;
if(p==="features")return `<div class="hero"><div><span class="eyebrow">FEATURE CONTROL</span><h1>Feature Access</h1></div></div><div class="card"><div class="features">${["New Phones","Second-Hand","Accessories","Inventory","Repairing","Billing PDF","Reports","Staff","AI Assistant","Advanced Analytics"].map(x=>`<div>✓ ${x}</div>`).join("")}</div></div>`;
return `<div class="hero"><div><span class="eyebrow">SUPER ADMIN</span><h1>Settings</h1></div></div><div class="card"><h3>Platform Settings</h3><p>Production में authentication, security, payment webhook और platform settings यहाँ manage होंगे।</p></div>`;
}
function shopPage(p){
const pages={
dashboard:`<div class="hero"><div><span class="eyebrow">${role==="staff"?"STAFF":"SHOP ADMIN"}</span><h1>दुकान का पूरा काम एक जगह।</h1><div class="muted">MEMORY Mobile Shop Workspace</div></div><button class="primary" onclick="render('sales')">+ New Sale</button></div><div class="stats">${stat("₹48,500","आज की Sales","+12.5%")}${stat("₹7,840","आज का Profit","+8.2%")}${stat("42","Phone Stock","8 low stock")}${stat("186","Accessories","24 sold")}</div><div class="section"><div class="grid">${tile("📱","New Phones","Stock & sale","phones")}${tile("♻","Second-Hand","Buy & sell","second")}${tile("◈","Accessories","Stock & sale","accessories")}${tile("⚒","Repairing","Job cards","repair")}</div></div><div class="section card">${table([["MEM-1042","Rahul","iPhone 15","₹55,000","PAID"],["MEM-1041","Aman","Accessories","₹7,499","PAID"],["MEM-1040","Neha","Samsung A56","₹34,999","DUE"]])}</div>`,
phones:shopModule("New Phone Management","Purchase, IMEI, stock, sale और profit.",["Add New Phone","In Stock","Sold Phones","IMEI Search"]),
second:shopModule("Second-Hand Management","Used phone purchase, checking और sale.",["Add Used Phone","Available Stock","Sold Phones","IMEI Search"]),
accessories:shopModule("Accessories","Quantity, purchase, stock और sale.",["Add Accessory","Stock","Low Stock","Sales"]),
purchase:shopModule("Purchase Management","Supplier और purchase records.",["New Purchase","Suppliers","Purchase History","Return"]),
sales:shopModule("Sales Management","Phone और accessories sales.",["New Sale","Sales History","Return","Due Sales"]),
inventory:shopModule("Inventory","Stock In, Stock Out और stock history.",["Stock Overview","Stock In","Stock Out","Low Stock"]),
repair:shopModule("Repairing","Job card से delivery तक.",["New Repair","In Repair","Ready","Delivered"]),
customers:shopModule("Customers","Customer purchase और repair history.",["Add Customer","All Customers","Search","Due Payments"]),
billing:shopModule("Billing & Invoice","Invoice generate, print और PDF.",["New Invoice","Invoice History","Due Bills","PDF / Print"]),
reports:shopModule("Reports & Analytics","Sales, profit, stock और repair reports.",["Daily","Monthly","Profit","Stock"]),
staff:shopModule("Staff Management","Staff users और permissions.",["Add Staff","All Staff","Permissions","Activity"]),
subscription:`<div class="hero"><div><span class="eyebrow">SHOP SUBSCRIPTION</span><h1>MEMORY Premium</h1><div class="muted">आपकी shop subscription.</div></div><button class="primary" onclick="toast('Payment Gateway integration point')">Renew Now</button></div><div class="card plan"><div><span class="badge">● ACTIVE</span><h3>Premium Plan</h3><div class="price">₹999 <small>/ month</small></div><div class="muted">Expiry: 22 September 2026 · 31 days remaining</div></div><button class="secondary" onclick="toast('Change Plan')">Change Plan</button></div>`
};return pages[p]||pages.dashboard}
function toggleSidebar(){$("sidebar").classList.toggle("open")}function toggleTheme(){document.body.classList.toggle("dark")}function toast(t){const x=$("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
